version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672" # RabbitMQ main port
      - "15672:15672" # RabbitMQ management plugin port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persist RabbitMQ data
volumes:
  rabbitmq_data: # Define a named volume for RabbitMQ data persistence
